repos:
  - docs.openfeature.dev
  - killercoda
  - playground
  - five-minutes-to-feature-flags
  - cloud-native-demo

approvers:
  - justinabrahms
  - beeme1mr
  - toddbaert
  - agardnerIT
  - moredip

maintainers: []

admins: []
