repos:
  - docs.openfeature.dev
  - openfeature.dev
  - killercoda
  - playground
  - five-minutes-to-feature-flags
  - cloud-native-demo

emeritus:
  - andrewdmaclean
  - agardnerIT

approvers:
  - justinabrahms
  - beeme1mr
  - toddbaert
  - moredip

maintainers: []

admins: []
