repos:
  - go-sdk-contrib

approvers: []

maintainers:
  - davejohnston
  - AlexsJones
  - Kavindu-Dodan
  - thomaspoignant
  - skyerus
  - james-milligan
  - toddbaert
  - beeme1mr
  - agentgonzo

admins: []
