repos:
  - kotlin-sdk
  - kotlin-sdk-contrib

emeritus: 
  - nickybondarenko

triagers:
  - cupofcat

approvers: 
  - bencehornak
  - typotter
  
maintainers:
  - fabriziodemaria
  - nicklasl
  - toddbaert
  - vahidlazio

admins: []
